platform: x64

environment:
  matrix:
    - TARGET: bmi2
    - TARGET: sse

install:
  - set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\local\bin;C:\msys64\usr\bin;C:\msys64\bin;%PATH%
  - set MSYSTEM=MINGW64
  - bash -lc "pacman --noconfirm -S base-devel mingw-w64-x86_64-toolchain mingw-w64-x86_64-clang mingw-w64-x86_64-cmake git unzip"

build_script:
  - bash -lc "cd $APPVEYOR_BUILD_FOLDER; mkdir build_msys2 && env && echo $TARGET && cd build_msys2 && cmake -Dtarget=$TARGET -G 'Unix Makefiles' ../src && make -j `nproc`"

before_test:
  - bash -lc "cd $APPVEYOR_BUILD_FOLDER; cp build_msys2/apery-by-clang.exe tests/ && mv build_msys2/apery-by-clang.exe build_msys2/silent_majority-by-clang-${TARGET}.exe && cd tests/ && ./all.sh"

artifacts:
  - path: build_msys2/silent_majority-by-clang-${TARGET}.exe
    name: nightly_build

